<table style="max-width:100%;border-collapse:collapse;border-spacing:0;width:100%;background-color:transparent;margin:0;padding:0; font-family: arial" bgcolor="transparent">
    <tbody>
        <tr style="margin:0;padding:0;">            
            <td style="margin:0;padding:0;"></td>
            <td bgcolor="#FFFFFF" style="display:block;max-width:600px !important;clear:both;margin:0 auto;padding:0;">
                <div style="max-width:600px;display:block;border-collapse:collapse;margin:0 auto;padding:30px 15px;border:1px solid #e7e7e7;">
                    <table style="max-width:100%;border-collapse:collapse;border-spacing:0;width:100%;background-color:transparent;margin:0;padding:0;" bgcolor="transparent">
                        <tbody>
                            <tr style="margin:0;padding:0;">
                                <td style="margin:0;padding:0;">
                                    <h2 style="line-height:24px;color:#000;font-weight:500;font-size:24px;margin:0 0 20px;padding:0;">Pesan Konfirmasi</h2>
                                    <p style="font-weight:normal;font-size:14px;line-height:1.6;margin:0;padding:0;">Anda diundang untuk bergabung dengan aplikasi <strong><?php echo $app; ?></strong>.</p>
                                    <p style="font-weight:normal;font-size:14px;line-height:1.6;margin:0px;padding:0;">Klik tombol di bawah ini untuk melakukan konfirmasi.</p>
                                    <p style="text-align: center;font-size: 28px; font-weight: bold;">
                                        <a href="<?php echo $href; ?>" style="width: 200px;display:inline-block;color: #ffffff;font-size: 12px;text-decoration: none;text-transform: uppercase;background-color: #3F51B5;border: 2px solid #3F51B5;;padding: 10px;text-align: center;">CONFIRM</a>
                                    </p>
                                    <p style="font-weight:normal;font-size:14px;line-height:1.6;margin-bottom:20px;padding:0; text-align: center;">atau buka link berikut</p>
                                    <p style="font-weight:normal;font-size:14px;line-height:1.6;margin:20px auto;padding:0; text-align: center; max-width:400px;">
                                        <a style="word-wrap: break-word;" href="<?php echo $href; ?>"><?php echo $href; ?></a>
                                    </p>
                                    
                                    <p style="font-weight:normal;font-size:14px;line-height:1.6;margin:0;padding:0;">Pesan ini berisi data sensitif, jangan teruskan (forward) pesan ini.</p>
                                    <p style="font-weight:normal;font-size:14px;line-height:1.6;margin:0;padding:0;">Jika ada pertanyaan, silahkan hubungi kami di: <span style="color:#4CACD7; font-weight: bold;"><?php echo $support; ?></span></p>

                                    <p style="font-weight:normal;font-size:14px;line-height:1.6;margin:10px 0;padding:0;">Terima kasih</p>
                                    
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </td>
            <td style="margin:0;padding:0;"></td>
        </tr>
    </tbody>
</table>